### ISSUE TITLE
douane-dialog not in path, start with full path?

### ISSUE THREAD

**Issue by junkvolny** [Douane/douane-dkms#12]
Citing from: https://github.com/Douane/Douane/wiki/Compilation
Now you need to start it:
douane-dialog &
And you should probably see it quit immediately.
---- end of citation

But it isn't in my $PATH variable, it required full path:
/opt/douane/bin/douane-dialog &

Maybe edit wiki? Or did I miss something again?

**Comment by zedtux** [comment]
You're right. The `make install` is installing Douane in the `/opt/` folder as I wanted to sell it (with the lower price) on the Ubuntu Software Center but I've failed to pass the USC checks (they hate kernel modules) so I will change that.

The long term solution will be to align with the standard which means installing Douane in the `/usr` folder.
For a short term solution, please find bellow my suggestion in order to solve the issue:

1. Open a pull request or
2. Add `/opt/douane/bin` to your `$PATH` or
3. Wait until I fix it :)

**Comment by junkvolny** [comment]
Or 4. you could just change line in wiki from
douane-dialog &
to:
/opt/douane/bin/douane-dialog &
;-)
My point is, when I first tried to copy-paste from wiki, it confused me, because it didn't work. I don't really care about installation paths, and I have no idea how to use pull requests.

**Comment by zedtux** [comment]
:smile: OK !

I'm doing it now but keep this issue open in order to update anyway the place where Douane is installed.

**Comment by zedtux** [comment]
Done.

**Comment by junkvolny** [comment]
Thanks. :-)

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-dkms/issues/12).
